Add `selectIndicesWhereOpConditions` method to `DataCategory`
rcsb/py-mmcif pull request #36
Opened 2024-12-23 16:49 UTC by brindakv

This PR adds `selectIndicesWhereOpConditions` method to `DataCategory`.

2025-01-07 13:52 UTC, piehld requested changes
@brindakv Overall LGTM. Just made one suggestion that might offer some slight efficiency improvement, but it's a little less intuitive, so will leave it up to you if it outweighs the readability. 

The only update I do request is adding a test in [testDataCategory.py](https://github.com/rcsb/py-mmcif/blob/master/mmcif/tests/testDataCategory.py) that tests these two new methods.

2025-01-07 16:03 UTC, epeisach reviewed
I am ok with code... A simple test would maintain coverage - ideally testing all conditionals - but that would take too much effort.

2025-01-08 17:35 UTC, epeisach approved these changes
I am ok with the change.  The added test uses Unicode but this is a restriction of CIF 1.0 - not the DataCategory class which does not have any such limitations.

2025-01-08 17:39 UTC, brindakv commented
Thanks @epeisach.

2025-01-08 18:14 UTC, piehld commented on mmcif/api/DataCategory.py
> +                        break
I'm noticing now that you have this `break` here whereas the other methods don't (e.g., `countValuesWhereOpConditions`). Should we add this to those other ones too? Seems like a logical efficiency to me, versus wasting time iterating over things once it's `False`.

2025-01-08 18:15 UTC, piehld approved these changes
Changes look good! Just had one other comment.

2025-01-08 18:38 UTC, brindakv commented
Thanks @piehld. Good point point about breaking the loop in other methods. Could we fix this in the next iteration?

2025-01-08 18:41 UTC, piehld commented
> Thanks @piehld. Good point about breaking the loop in other methods. Could we fix this in the next iteration?

Sure. Think we should add a comment in the code as a reminder, or no?

2025-01-08 18:53 UTC, brindakv commented
`pylint` gives random errors with each push. I would prefer to avoid it if possible. I can create an issue as a reminder.

2025-01-08 18:58 UTC, piehld commented
Weird. I could see pylint presenting a problem if there's no space between the `#` and the comment (also, I think there needs to be exactly 2 spaces preceding the `#`). But anyway, creating an issue sounds like a better solution. Thanks.

2025-01-08 19:12 UTC, brindakv commented
@piehld Here is the new issue: https://github.com/rcsb/py-mmcif/issues/37

Merging this PR now.

2025-01-08 19:12 UTC, merged